### ISSUE TITLE
Error Playing Channel

### ISSUE THREAD

**Issue by tauhidulislamzisan** [Shadmanislam/bdiptv#1]
I've tried to play channels using VLC on laptop it's showing unable to play Up to 70% channels. On android with IPTV app error playing channels. I have checked the links with http://www.iptvtools.net/  channels are online but when i click on watch live streams it's showing ''Viewing is not available.''

**Comment by Shadmanislam** [comment]
Use MyIPTV Player (Windows) : https://bit.ly/2VoB33Q

**Comment by sobuj53** [comment]
I've downloaded MyIPTVPlayer and added [m3u](https://raw.githubusercontent.com/Shadmanislam/bdiptv/master/BD%20IPTV.m3u) link the custom channel. But it's not playing, **Error: Unsupported video type or invalid file path**. Also tried with vlc, but same. I would really appreciate if you could take a look.
